name: pb_dtos
description: "A code generator for PocketBase DTOs."
version: 0.2.0
repository: "https://github.com/brigham/pb_dtos"

environment:
  sdk: ^3.10.0

dependencies:
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  meta: ^1.16.0
  pocketbase: ^0.23.0+1
  csv: ^6.0.0
  yaml: ^3.1.3
  args: ^2.7.0
  path: ^1.9.1
  dcli: ^8.2.0
  mustache_template: ^2.0.2
  dart_style: ^3.1.3
  recase: ^4.1.0
  json_serializable: ^6.11.2
  archive: ^4.0.7
  crypto: ^3.0.7

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.2
  mockito: ^5.5.1
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_annotation: ^4.9.0
